a = input()
b = input()
sum1 = str(int(a) * int(b[2]))
sum2 = str((int(a)*10) * int(b[1]))
sum3 = str((int(a)*100) * int(b[0]))
sum4 = int(sum1) + int(sum2[:5]) + int(sum3[:6])
print(sum1)
print(sum2[:4])
print(sum3[:4])
print(sum4)