#include <stdio.h>
int main()
{
    int interfaceofthefastapiofpythonandjavaandjavascriptorcorspringpringandnodejsandreactandvueandangularandhtmlandcssandjavascriptandtypescriptandcsharpanddotnetandmysqlandmariadbandsqliteandmongodbandredisandcassandraandpostgresqlandoracleanddb2andsybaseandsqlserver;
    interfaceofthefastapiofpythonandjavaandjavascriptorcorspringpringandnodejsandreactandvueandangularandhtmlandcssandjavascriptandtypescriptandcsharpanddotnetandmysqlandmariadbandsqliteandmongodbandredisandcassandraandpostgresqlandoracleanddb2andsybaseandsqlserver= 100;
    printf("%d\n", interfaceofthefastapiofpythonandjavaandjavascriptorcorspringpringandnodejsandreactandvueandangularandhtmlandcssandjavascriptandtypescriptandcsharpanddotnetandmysqlandmariadbandsqliteandmongodbandredisandcassandraandpostgresqlandoracleanddb2andsybaseandsqlserver);
    if(interfaceofthefastapiofpythonandjavaandjavascriptorcorspringpringandnodejsandreactandvueandangularandhtmlandcssandjavascriptandtypescriptandcsharpanddotnetandmysqlandmariadbandsqliteandmongodbandredisandcassandraandpostgresqlandoracleanddb2andsybaseandsqlserver==100)
    {
        printf("Hello World\n");
    }
    
}